#!/bin/zsh

get_icons() {
    local session_name="$1"
    local result=""

  local panes=($(tmux list-panes -t "$session_name" -F '#{pane_current_command}'))

  for i in "${panes[@]}"; do
      case "$i" in
          nvim) result+=" " ;;
          ssh) result+="󰒒 " ;;
          meow) result+=" " ;;
          nano) result+=" " ;;
          cargo) result+=" " ;;
          maid) result+="󰃢 " ;;
          pnpm) result+=" " ;;
          node) result+="⬢ " ;;
          ncdu) result+=" " ;;
          htop | btop | top | pumas) result+="󱔓 " ;;
          zsh | *) result+=" " ;;
      esac
  done

    echo "$result"
}

if (( $# != 1 )); then
    echo "Usage: $0 <session-name>"
    exit 1
fi

get_icons "$1"
