# This is an example configuration file for meow editor.
# Uncomment and modify the values as needed.

# Disable mouse interaction (default: false)
# disable_mouse_interaction = false

# Set tab width (default: 4)
# tab_width = 4

# Set theme (default: none)
# theme = "monokai"

# Use relative line numbers (default: false)
# relative_line_numbers = false

# Keybinds configuration
# Format: "Modifier+Key" (e.g., "Ctrl+S", "Alt+X")
# Available modifiers: Ctrl, Alt, Shift
# For special keys, use their names (e.g., "Enter", "Backspace", "Tab")
# [keybinds]
# quit = "Ctrl+Q"
# save = "Ctrl+S"
# discard_changes = "Ctrl+A"
# undo = "Ctrl+Z"
# redo = "Ctrl+Y"
# copy = "Ctrl+C"
# paste = "Ctrl+V"
# cut = "Ctrl+X"
# system_copy = "Alt+C"
# system_paste = "Alt+V"
# system_cut = "Alt+X"
# move_up = "Up"
# move_down = "Down"
# move_left = "Left"
# move_right = "Right"
# move_word_left = "Ctrl+Left"
# move_word_right = "Ctrl+Right"
# move_to_start_of_line = "Home"
# move_to_end_of_line = "End"
# page_up = "PageUp"
# page_down = "PageDown"
# half_page_up = "Ctrl+U"
# half_page_down = "Ctrl+D"
